# Generated by Django 4.1.7 on 2023-04-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='variant',
            field=models.CharField(choices=[('1 variant', '1 variant'), ('2 variant', '2 variant'), ('3 variant', '3 variant')], max_length=25),
        ),
    ]
