# Generated by Django 4.1.7 on 2023-05-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPredictionViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDataModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('database_type', models.CharField(choices=[('Cricket', 'Cricket'), ('Mobile', 'Mobile'), ('Technology', 'Technology')], max_length=30)),
                ('label', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='content',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='content',
            name='variant',
            field=models.CharField(choices=[('Cricket', 'Cricket'), ('Mobile', 'Mobile'), ('Technology', 'Technology')], max_length=30),
        ),
    ]
