# Generated by Django 4.1.7 on 2023-05-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_datapredictionviews_userdatamodels_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPredictionViews',
        ),
    ]
