# Generated by Django 4.1.7 on 2023-06-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_urltable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urltable',
            old_name='pdf',
            new_name='url',
        ),
    ]
