# Generated by Django 4.1.7 on 2023-08-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_userdatabasename'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionAndAnswr',
            new_name='QuestionAndAnswer',
        ),
    ]
