# Generated by Django 4.1.7 on 2023-06-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_pdf_urltable_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_pdf',
            name='pdf_filename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
