# Generated by Django 4.1.7 on 2023-06-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_user_pdf_pdf_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cricket_Question_and_Answer',
        ),
        migrations.DeleteModel(
            name='Mobile_Technology_Waves',
        ),
        migrations.DeleteModel(
            name='Technologies',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
