# Generated by Django 4.1.7 on 2023-06-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_content_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Label',
        ),
        migrations.AddField(
            model_name='questionandanswr',
            name='user_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
