# Generated by Django 4.1.7 on 2023-06-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_topic_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='Topic',
            new_name='topic_name',
        ),
        migrations.RemoveField(
            model_name='questionandanswr',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user_id',
        ),
    ]
