# Generated by Django 4.1.7 on 2023-06-12 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_rename_topic_topic_topic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswr',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
